/* tslint:disable */
/* eslint-disable */
/**
 * Gen Z Validation
 * Mejor tipado, menos boilerplate.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PowerRangersSeasons,
    PowerRangersSeasonsFromJSON,
    PowerRangersSeasonsFromJSONTyped,
    PowerRangersSeasonsToJSON,
} from './';

/**
 * Go Go Power Rangers
 * @export
 * @interface PorwerRanger
 */
export interface PorwerRanger {
    /**
     * 
     * @type {number}
     * @memberof PorwerRanger
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PorwerRanger
     */
    name: string;
    /**
     * 
     * @type {Array<PowerRangersSeasons>}
     * @memberof PorwerRanger
     */
    seasons: Array<PowerRangersSeasons>;
}

export function PorwerRangerFromJSON(json: any): PorwerRanger {
    return PorwerRangerFromJSONTyped(json, false);
}

export function PorwerRangerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PorwerRanger {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'seasons': ((json['seasons'] as Array<any>).map(PowerRangersSeasonsFromJSON)),
    };
}

export function PorwerRangerToJSON(value?: PorwerRanger | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'seasons': ((value.seasons as Array<any>).map(PowerRangersSeasonsToJSON)),
    };
}

