/* tslint:disable */
/* eslint-disable */
/**
 * Gen Z Validation
 * Kneel before zod
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PowerRangerSeasons
 */
export interface PowerRangerSeasons {
    /**
     * 
     * @type {string}
     * @memberof PowerRangerSeasons
     */
    season: PowerRangerSeasonsSeasonEnum;
    /**
     * 
     * @type {string}
     * @memberof PowerRangerSeasons
     */
    color: PowerRangerSeasonsColorEnum;
}

/**
* @export
* @enum {string}
*/
export enum PowerRangerSeasonsSeasonEnum {
    _1 = '1',
    _2 = '2',
    _3 = '3',
    zeo = 'zeo'
}/**
* @export
* @enum {string}
*/
export enum PowerRangerSeasonsColorEnum {
    red = 'red',
    yellow = 'yellow',
    black = 'black',
    pink = 'pink',
    blue = 'blue',
    green = 'green',
    white = 'white',
    gold = 'gold'
}

export function PowerRangerSeasonsFromJSON(json: any): PowerRangerSeasons {
    return PowerRangerSeasonsFromJSONTyped(json, false);
}

export function PowerRangerSeasonsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerRangerSeasons {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'season': json['season'],
        'color': json['color'],
    };
}

export function PowerRangerSeasonsToJSON(value?: PowerRangerSeasons | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'season': value.season,
        'color': value.color,
    };
}

